package org.hmx.utils.storage.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DivisionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_division
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_division
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_division
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public DivisionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_division
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOilregIdIsNull() {
            addCriterion("oilreg_id is null");
            return (Criteria) this;
        }

        public Criteria andOilregIdIsNotNull() {
            addCriterion("oilreg_id is not null");
            return (Criteria) this;
        }

        public Criteria andOilregIdEqualTo(Long value) {
            addCriterion("oilreg_id =", value, "oilregId");
            return (Criteria) this;
        }

        public Criteria andOilregIdNotEqualTo(Long value) {
            addCriterion("oilreg_id <>", value, "oilregId");
            return (Criteria) this;
        }

        public Criteria andOilregIdGreaterThan(Long value) {
            addCriterion("oilreg_id >", value, "oilregId");
            return (Criteria) this;
        }

        public Criteria andOilregIdGreaterThanOrEqualTo(Long value) {
            addCriterion("oilreg_id >=", value, "oilregId");
            return (Criteria) this;
        }

        public Criteria andOilregIdLessThan(Long value) {
            addCriterion("oilreg_id <", value, "oilregId");
            return (Criteria) this;
        }

        public Criteria andOilregIdLessThanOrEqualTo(Long value) {
            addCriterion("oilreg_id <=", value, "oilregId");
            return (Criteria) this;
        }

        public Criteria andOilregIdIn(List<Long> values) {
            addCriterion("oilreg_id in", values, "oilregId");
            return (Criteria) this;
        }

        public Criteria andOilregIdNotIn(List<Long> values) {
            addCriterion("oilreg_id not in", values, "oilregId");
            return (Criteria) this;
        }

        public Criteria andOilregIdBetween(Long value1, Long value2) {
            addCriterion("oilreg_id between", value1, value2, "oilregId");
            return (Criteria) this;
        }

        public Criteria andOilregIdNotBetween(Long value1, Long value2) {
            addCriterion("oilreg_id not between", value1, value2, "oilregId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("store_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("store_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(Long value) {
            addCriterion("store_id =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(Long value) {
            addCriterion("store_id <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(Long value) {
            addCriterion("store_id >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(Long value) {
            addCriterion("store_id >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(Long value) {
            addCriterion("store_id <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(Long value) {
            addCriterion("store_id <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<Long> values) {
            addCriterion("store_id in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<Long> values) {
            addCriterion("store_id not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(Long value1, Long value2) {
            addCriterion("store_id between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(Long value1, Long value2) {
            addCriterion("store_id not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdIsNull() {
            addCriterion("oiltank_id is null");
            return (Criteria) this;
        }

        public Criteria andOiltankIdIsNotNull() {
            addCriterion("oiltank_id is not null");
            return (Criteria) this;
        }

        public Criteria andOiltankIdEqualTo(Long value) {
            addCriterion("oiltank_id =", value, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdNotEqualTo(Long value) {
            addCriterion("oiltank_id <>", value, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdGreaterThan(Long value) {
            addCriterion("oiltank_id >", value, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdGreaterThanOrEqualTo(Long value) {
            addCriterion("oiltank_id >=", value, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdLessThan(Long value) {
            addCriterion("oiltank_id <", value, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdLessThanOrEqualTo(Long value) {
            addCriterion("oiltank_id <=", value, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdIn(List<Long> values) {
            addCriterion("oiltank_id in", values, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdNotIn(List<Long> values) {
            addCriterion("oiltank_id not in", values, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdBetween(Long value1, Long value2) {
            addCriterion("oiltank_id between", value1, value2, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOiltankIdNotBetween(Long value1, Long value2) {
            addCriterion("oiltank_id not between", value1, value2, "oiltankId");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreIsNull() {
            addCriterion("oil_mass_litre is null");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreIsNotNull() {
            addCriterion("oil_mass_litre is not null");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreEqualTo(Float value) {
            addCriterion("oil_mass_litre =", value, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreNotEqualTo(Float value) {
            addCriterion("oil_mass_litre <>", value, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreGreaterThan(Float value) {
            addCriterion("oil_mass_litre >", value, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreGreaterThanOrEqualTo(Float value) {
            addCriterion("oil_mass_litre >=", value, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreLessThan(Float value) {
            addCriterion("oil_mass_litre <", value, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreLessThanOrEqualTo(Float value) {
            addCriterion("oil_mass_litre <=", value, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreIn(List<Float> values) {
            addCriterion("oil_mass_litre in", values, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreNotIn(List<Float> values) {
            addCriterion("oil_mass_litre not in", values, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreBetween(Float value1, Float value2) {
            addCriterion("oil_mass_litre between", value1, value2, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilMassLitreNotBetween(Float value1, Float value2) {
            addCriterion("oil_mass_litre not between", value1, value2, "oilMassLitre");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalIsNull() {
            addCriterion("oil_costtotal is null");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalIsNotNull() {
            addCriterion("oil_costtotal is not null");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalEqualTo(Long value) {
            addCriterion("oil_costtotal =", value, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalNotEqualTo(Long value) {
            addCriterion("oil_costtotal <>", value, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalGreaterThan(Long value) {
            addCriterion("oil_costtotal >", value, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalGreaterThanOrEqualTo(Long value) {
            addCriterion("oil_costtotal >=", value, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalLessThan(Long value) {
            addCriterion("oil_costtotal <", value, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalLessThanOrEqualTo(Long value) {
            addCriterion("oil_costtotal <=", value, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalIn(List<Long> values) {
            addCriterion("oil_costtotal in", values, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalNotIn(List<Long> values) {
            addCriterion("oil_costtotal not in", values, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalBetween(Long value1, Long value2) {
            addCriterion("oil_costtotal between", value1, value2, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andOilCosttotalNotBetween(Long value1, Long value2) {
            addCriterion("oil_costtotal not between", value1, value2, "oilCosttotal");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNull() {
            addCriterion("total_amount is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNotNull() {
            addCriterion("total_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountEqualTo(Long value) {
            addCriterion("total_amount =", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotEqualTo(Long value) {
            addCriterion("total_amount <>", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThan(Long value) {
            addCriterion("total_amount >", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("total_amount >=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThan(Long value) {
            addCriterion("total_amount <", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThanOrEqualTo(Long value) {
            addCriterion("total_amount <=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIn(List<Long> values) {
            addCriterion("total_amount in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotIn(List<Long> values) {
            addCriterion("total_amount not in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountBetween(Long value1, Long value2) {
            addCriterion("total_amount between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotBetween(Long value1, Long value2) {
            addCriterion("total_amount not between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNull() {
            addCriterion("total_count is null");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNotNull() {
            addCriterion("total_count is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCountEqualTo(Integer value) {
            addCriterion("total_count =", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotEqualTo(Integer value) {
            addCriterion("total_count <>", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThan(Integer value) {
            addCriterion("total_count >", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_count >=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThan(Integer value) {
            addCriterion("total_count <", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThanOrEqualTo(Integer value) {
            addCriterion("total_count <=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountIn(List<Integer> values) {
            addCriterion("total_count in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotIn(List<Integer> values) {
            addCriterion("total_count not in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountBetween(Integer value1, Integer value2) {
            addCriterion("total_count between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotBetween(Integer value1, Integer value2) {
            addCriterion("total_count not between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalLitreIsNull() {
            addCriterion("total_litre is null");
            return (Criteria) this;
        }

        public Criteria andTotalLitreIsNotNull() {
            addCriterion("total_litre is not null");
            return (Criteria) this;
        }

        public Criteria andTotalLitreEqualTo(Float value) {
            addCriterion("total_litre =", value, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andTotalLitreNotEqualTo(Float value) {
            addCriterion("total_litre <>", value, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andTotalLitreGreaterThan(Float value) {
            addCriterion("total_litre >", value, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andTotalLitreGreaterThanOrEqualTo(Float value) {
            addCriterion("total_litre >=", value, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andTotalLitreLessThan(Float value) {
            addCriterion("total_litre <", value, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andTotalLitreLessThanOrEqualTo(Float value) {
            addCriterion("total_litre <=", value, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andTotalLitreIn(List<Float> values) {
            addCriterion("total_litre in", values, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andTotalLitreNotIn(List<Float> values) {
            addCriterion("total_litre not in", values, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andTotalLitreBetween(Float value1, Float value2) {
            addCriterion("total_litre between", value1, value2, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andTotalLitreNotBetween(Float value1, Float value2) {
            addCriterion("total_litre not between", value1, value2, "totalLitre");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDivAmountIsNull() {
            addCriterion("div_amount is null");
            return (Criteria) this;
        }

        public Criteria andDivAmountIsNotNull() {
            addCriterion("div_amount is not null");
            return (Criteria) this;
        }

        public Criteria andDivAmountEqualTo(Long value) {
            addCriterion("div_amount =", value, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivAmountNotEqualTo(Long value) {
            addCriterion("div_amount <>", value, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivAmountGreaterThan(Long value) {
            addCriterion("div_amount >", value, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("div_amount >=", value, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivAmountLessThan(Long value) {
            addCriterion("div_amount <", value, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivAmountLessThanOrEqualTo(Long value) {
            addCriterion("div_amount <=", value, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivAmountIn(List<Long> values) {
            addCriterion("div_amount in", values, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivAmountNotIn(List<Long> values) {
            addCriterion("div_amount not in", values, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivAmountBetween(Long value1, Long value2) {
            addCriterion("div_amount between", value1, value2, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivAmountNotBetween(Long value1, Long value2) {
            addCriterion("div_amount not between", value1, value2, "divAmount");
            return (Criteria) this;
        }

        public Criteria andDivCountIsNull() {
            addCriterion("div_count is null");
            return (Criteria) this;
        }

        public Criteria andDivCountIsNotNull() {
            addCriterion("div_count is not null");
            return (Criteria) this;
        }

        public Criteria andDivCountEqualTo(Integer value) {
            addCriterion("div_count =", value, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivCountNotEqualTo(Integer value) {
            addCriterion("div_count <>", value, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivCountGreaterThan(Integer value) {
            addCriterion("div_count >", value, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("div_count >=", value, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivCountLessThan(Integer value) {
            addCriterion("div_count <", value, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivCountLessThanOrEqualTo(Integer value) {
            addCriterion("div_count <=", value, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivCountIn(List<Integer> values) {
            addCriterion("div_count in", values, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivCountNotIn(List<Integer> values) {
            addCriterion("div_count not in", values, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivCountBetween(Integer value1, Integer value2) {
            addCriterion("div_count between", value1, value2, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivCountNotBetween(Integer value1, Integer value2) {
            addCriterion("div_count not between", value1, value2, "divCount");
            return (Criteria) this;
        }

        public Criteria andDivLitreIsNull() {
            addCriterion("div_litre is null");
            return (Criteria) this;
        }

        public Criteria andDivLitreIsNotNull() {
            addCriterion("div_litre is not null");
            return (Criteria) this;
        }

        public Criteria andDivLitreEqualTo(Float value) {
            addCriterion("div_litre =", value, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivLitreNotEqualTo(Float value) {
            addCriterion("div_litre <>", value, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivLitreGreaterThan(Float value) {
            addCriterion("div_litre >", value, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivLitreGreaterThanOrEqualTo(Float value) {
            addCriterion("div_litre >=", value, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivLitreLessThan(Float value) {
            addCriterion("div_litre <", value, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivLitreLessThanOrEqualTo(Float value) {
            addCriterion("div_litre <=", value, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivLitreIn(List<Float> values) {
            addCriterion("div_litre in", values, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivLitreNotIn(List<Float> values) {
            addCriterion("div_litre not in", values, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivLitreBetween(Float value1, Float value2) {
            addCriterion("div_litre between", value1, value2, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivLitreNotBetween(Float value1, Float value2) {
            addCriterion("div_litre not between", value1, value2, "divLitre");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeIsNull() {
            addCriterion("div_starttime is null");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeIsNotNull() {
            addCriterion("div_starttime is not null");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeEqualTo(Date value) {
            addCriterion("div_starttime =", value, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeNotEqualTo(Date value) {
            addCriterion("div_starttime <>", value, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeGreaterThan(Date value) {
            addCriterion("div_starttime >", value, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("div_starttime >=", value, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeLessThan(Date value) {
            addCriterion("div_starttime <", value, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("div_starttime <=", value, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeIn(List<Date> values) {
            addCriterion("div_starttime in", values, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeNotIn(List<Date> values) {
            addCriterion("div_starttime not in", values, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeBetween(Date value1, Date value2) {
            addCriterion("div_starttime between", value1, value2, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andDivStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("div_starttime not between", value1, value2, "divStarttime");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdIsNull() {
            addCriterion("trigger1_payment_id is null");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdIsNotNull() {
            addCriterion("trigger1_payment_id is not null");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdEqualTo(Long value) {
            addCriterion("trigger1_payment_id =", value, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdNotEqualTo(Long value) {
            addCriterion("trigger1_payment_id <>", value, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdGreaterThan(Long value) {
            addCriterion("trigger1_payment_id >", value, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("trigger1_payment_id >=", value, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdLessThan(Long value) {
            addCriterion("trigger1_payment_id <", value, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdLessThanOrEqualTo(Long value) {
            addCriterion("trigger1_payment_id <=", value, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdIn(List<Long> values) {
            addCriterion("trigger1_payment_id in", values, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdNotIn(List<Long> values) {
            addCriterion("trigger1_payment_id not in", values, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdBetween(Long value1, Long value2) {
            addCriterion("trigger1_payment_id between", value1, value2, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1PaymentIdNotBetween(Long value1, Long value2) {
            addCriterion("trigger1_payment_id not between", value1, value2, "trigger1PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountIsNull() {
            addCriterion("trigger1_divamount is null");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountIsNotNull() {
            addCriterion("trigger1_divamount is not null");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountEqualTo(Long value) {
            addCriterion("trigger1_divamount =", value, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountNotEqualTo(Long value) {
            addCriterion("trigger1_divamount <>", value, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountGreaterThan(Long value) {
            addCriterion("trigger1_divamount >", value, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountGreaterThanOrEqualTo(Long value) {
            addCriterion("trigger1_divamount >=", value, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountLessThan(Long value) {
            addCriterion("trigger1_divamount <", value, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountLessThanOrEqualTo(Long value) {
            addCriterion("trigger1_divamount <=", value, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountIn(List<Long> values) {
            addCriterion("trigger1_divamount in", values, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountNotIn(List<Long> values) {
            addCriterion("trigger1_divamount not in", values, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountBetween(Long value1, Long value2) {
            addCriterion("trigger1_divamount between", value1, value2, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger1DivamountNotBetween(Long value1, Long value2) {
            addCriterion("trigger1_divamount not between", value1, value2, "trigger1Divamount");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeIsNull() {
            addCriterion("div_endttime is null");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeIsNotNull() {
            addCriterion("div_endttime is not null");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeEqualTo(Date value) {
            addCriterion("div_endttime =", value, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeNotEqualTo(Date value) {
            addCriterion("div_endttime <>", value, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeGreaterThan(Date value) {
            addCriterion("div_endttime >", value, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("div_endttime >=", value, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeLessThan(Date value) {
            addCriterion("div_endttime <", value, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeLessThanOrEqualTo(Date value) {
            addCriterion("div_endttime <=", value, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeIn(List<Date> values) {
            addCriterion("div_endttime in", values, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeNotIn(List<Date> values) {
            addCriterion("div_endttime not in", values, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeBetween(Date value1, Date value2) {
            addCriterion("div_endttime between", value1, value2, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andDivEndttimeNotBetween(Date value1, Date value2) {
            addCriterion("div_endttime not between", value1, value2, "divEndttime");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdIsNull() {
            addCriterion("trigger2_payment_id is null");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdIsNotNull() {
            addCriterion("trigger2_payment_id is not null");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdEqualTo(Long value) {
            addCriterion("trigger2_payment_id =", value, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdNotEqualTo(Long value) {
            addCriterion("trigger2_payment_id <>", value, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdGreaterThan(Long value) {
            addCriterion("trigger2_payment_id >", value, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("trigger2_payment_id >=", value, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdLessThan(Long value) {
            addCriterion("trigger2_payment_id <", value, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdLessThanOrEqualTo(Long value) {
            addCriterion("trigger2_payment_id <=", value, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdIn(List<Long> values) {
            addCriterion("trigger2_payment_id in", values, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdNotIn(List<Long> values) {
            addCriterion("trigger2_payment_id not in", values, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdBetween(Long value1, Long value2) {
            addCriterion("trigger2_payment_id between", value1, value2, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2PaymentIdNotBetween(Long value1, Long value2) {
            addCriterion("trigger2_payment_id not between", value1, value2, "trigger2PaymentId");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountIsNull() {
            addCriterion("trigger2_divamount is null");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountIsNotNull() {
            addCriterion("trigger2_divamount is not null");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountEqualTo(Long value) {
            addCriterion("trigger2_divamount =", value, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountNotEqualTo(Long value) {
            addCriterion("trigger2_divamount <>", value, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountGreaterThan(Long value) {
            addCriterion("trigger2_divamount >", value, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountGreaterThanOrEqualTo(Long value) {
            addCriterion("trigger2_divamount >=", value, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountLessThan(Long value) {
            addCriterion("trigger2_divamount <", value, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountLessThanOrEqualTo(Long value) {
            addCriterion("trigger2_divamount <=", value, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountIn(List<Long> values) {
            addCriterion("trigger2_divamount in", values, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountNotIn(List<Long> values) {
            addCriterion("trigger2_divamount not in", values, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountBetween(Long value1, Long value2) {
            addCriterion("trigger2_divamount between", value1, value2, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andTrigger2DivamountNotBetween(Long value1, Long value2) {
            addCriterion("trigger2_divamount not between", value1, value2, "trigger2Divamount");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeIsNull() {
            addCriterion("match_oiltype is null");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeIsNotNull() {
            addCriterion("match_oiltype is not null");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeEqualTo(Integer value) {
            addCriterion("match_oiltype =", value, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeNotEqualTo(Integer value) {
            addCriterion("match_oiltype <>", value, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeGreaterThan(Integer value) {
            addCriterion("match_oiltype >", value, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("match_oiltype >=", value, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeLessThan(Integer value) {
            addCriterion("match_oiltype <", value, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeLessThanOrEqualTo(Integer value) {
            addCriterion("match_oiltype <=", value, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeIn(List<Integer> values) {
            addCriterion("match_oiltype in", values, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeNotIn(List<Integer> values) {
            addCriterion("match_oiltype not in", values, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeBetween(Integer value1, Integer value2) {
            addCriterion("match_oiltype between", value1, value2, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andMatchOiltypeNotBetween(Integer value1, Integer value2) {
            addCriterion("match_oiltype not between", value1, value2, "matchOiltype");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdIsNull() {
            addCriterion("oil_type_id is null");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdIsNotNull() {
            addCriterion("oil_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdEqualTo(Long value) {
            addCriterion("oil_type_id =", value, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdNotEqualTo(Long value) {
            addCriterion("oil_type_id <>", value, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdGreaterThan(Long value) {
            addCriterion("oil_type_id >", value, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("oil_type_id >=", value, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdLessThan(Long value) {
            addCriterion("oil_type_id <", value, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("oil_type_id <=", value, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdIn(List<Long> values) {
            addCriterion("oil_type_id in", values, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdNotIn(List<Long> values) {
            addCriterion("oil_type_id not in", values, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdBetween(Long value1, Long value2) {
            addCriterion("oil_type_id between", value1, value2, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andOilTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("oil_type_id not between", value1, value2, "oilTypeId");
            return (Criteria) this;
        }

        public Criteria andRfAmountIsNull() {
            addCriterion("rf_amount is null");
            return (Criteria) this;
        }

        public Criteria andRfAmountIsNotNull() {
            addCriterion("rf_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRfAmountEqualTo(Long value) {
            addCriterion("rf_amount =", value, "rfAmount");
            return (Criteria) this;
        }

        public Criteria andRfAmountNotEqualTo(Long value) {
            addCriterion("rf_amount <>", value, "rfAmount");
            return (Criteria) this;
        }

        public Criteria andRfAmountGreaterThan(Long value) {
            addCriterion("rf_amount >", value, "rfAmount");
            return (Criteria) this;
        }

        public Criteria andRfAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("rf_amount >=", value, "rfAmount");
            return (Criteria) this;
        }

        public Criteria andRfAmountLessThan(Long value) {
            addCriterion("rf_amount <", value, "rfAmount");
            return (Criteria) this;
        }

        public Criteria andRfAmountLessThanOrEqualTo(Long value) {
            addCriterion("rf_amount <=", value, "rfAmount");
            return (Criteria) this;
        }

        public Criteria andRfAmountIn(List<Long> values) {
            addCriterion("rf_amount in", values, "rfAmount");
            return (Criteria) this;
        }

        public Criteria andRfAmountNotIn(List<Long> values) {
            addCriterion("rf_amount not in", values, "rfAmount");
            return (Criteria) this;
        }

        public Criteria andRfAmountBetween(Long value1, Long value2) {
            addCriterion("rf_amount between", value1, value2, "rfAmount");
            return (Criteria) this;
        }

        public Criteria andRfAmountNotBetween(Long value1, Long value2) {
            addCriterion("rf_amount not between", value1, value2, "rfAmount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_division
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_division
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}